language: node_js

sudo: required

services:
  - docker

node_js:
  - "18"

arch:
  - amd64

os: 
  - linux

install:
  - npm install

  # Compile OpenCV
  - bash ./utils/buildcombined.sh

  # Create types
  - bash ./utils/generateTypes.sh

  # Install test node modules
  - (cd ./build_wasm_test/bin && npm install)


script:
  # Run opencv's test
  - (cd ./build_wasm_test/bin && node tests.js)
  # Run opencv-wasm's test
  - npm test
